Import('env')

shared_obj = env.SharedObject('a.c')
# env.SharedLibrary('noversion', shared_obj)
#
# env.SharedLibrary('a', shared_obj, SHLIBVERSION='1.2.3')
# env.SharedLibrary('a_soversion', shared_obj, SHLIBVERSION='1.2.3', SOVERSION='3')
# env.SharedLibrary('a_soname', shared_obj, SHLIBVERSION='1.2.3', SONAME='liba_soname.9.so')
# env.SharedLibrary('a_nosymlink', shared_obj, SHLIBVERSION='1.2.3', SHLIBNOVERSIONSYMLINKS=True)


env.LoadableModule('loadable_a', shared_obj, LDMODULEVERSION='1.2.3')
env.LoadableModule('loadable_a_soversion', shared_obj, LDMODULEVERSION='1.2.3', SOVERSION='4')
env.LoadableModule('loadable_a_soname', shared_obj, LDMODULEVERSION='1.2.3', SONAME='libloadable_a_soname.99.so')
env.LoadableModule('loadable_a_nosymlink', shared_obj, LDMODULEVERSION='3.4.5', LDMODULENOVERSIONSYMLINKS=True)

if env.get('APPLE_TESTS', False):
    # Now do apple specific tests
    env.SharedLibrary('a_compat_version', shared_obj, APPLELINK_COMPATIBILITY_VERSION='1.2.3')
    env.SharedLibrary('a_current_version', shared_obj, APPLELINK_CURRENT_VERSION='1.2.3')

    # env.SharedLibrary('a_compat_noversion', shared_obj, SHLIBVERSION='1.2.3', APPLELINK_NO_COMPATIBILITY_VERSION=True)
    # env.SharedLibrary('a_soname', shared_obj, SHLIBVERSION='1.2.3', SONAME='liba_soname.9.so')
    # env.SharedLibrary('a_nosymlink', shared_obj, SHLIBVERSION='1.2.3', SHLIBNOVERSIONSYMLINKS=True)


if env.get('CYGWIN_TESTS', False):
    # Cygwin
    # On diff. instead of libxyz.1.2.3.so  it should be cygxyz-1-2-3.dll
    # for implib libxyz-1-2-3.dll.a
    # NOTE: the 'lib' is on the implib, but NOT on the shared library
    # NOTE: Symlinks only for imp lib and not for dll.
    # so: libxyz.dll.a -> libxyz-1-2-3.dll.a
    #     and no other.
    env.SharedLibrary('noversion_noimportlib', shared_obj, no_import_lib=True)
    env.SharedLibrary('shared_lib_version_no_importlib', shared_obj, SHLIBVERSION='1.2.3', no_import_lib=True)
    # Need
    # gcc -o build/cygwin/cyga-1-2-3.dll -Wl,-no-undefined -shared -Wl,--out-implib=build/cygwin/liba-1-2-3.dll.a -Wl,--export-all-symbols -Wl,--enable-auto-import -Wl,--whole-archive build/cygwin/a.os -Wl,--no-whole-archive
    # vs
    # gcc -o build/cygwin/cyga.dll.1.2.3 -Wl,-no-undefined -shared   build/cygwin/a.os $(  $)
